---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: grafana-operator
  namespace: kube-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: grafana-operator
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get", "watch", "list"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: grafana-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: grafana-operator
  namespace: kube-system

---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: grafana-operator
  namespace: kube-system
  labels:
    k8s-app: grafana-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: grafana-operator
    spec:
      serviceAccountName: grafana-operator
      containers:
      - image: tsloughter/grafana-operator:latest
        name: grafana-operator
